services:
  - type: static
    name: devcard
    buildCommand: |
      corepack enable
      corepack prepare pnpm@8 --activate
      pnpm -v
      pnpm install --frozen-lockfile
      pnpm run build
    staticPublishPath: dist
