services:
  - type: static
    name: my-react-site
    buildCommand: pnpm i --frozen-lockfile && pnpm build
    publishPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
